server {
    listen 80;
    server_name localhost;

    location /_next/static/ {
        alias /next-static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files /next-public$uri /next-public$uri/ @backend;
    }

    location @backend {
        proxy_pass http://playground_nextjs:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
